### ISSUE TITLE
What is the "result_r_t.txt" and "scale"

### ISSUE THREAD

**Issue by li19960612** [gg-z/opengl_render_img_in_a_specific_view#1]
I read your "render_one_pic_according_camera_paras.cpp" code. Can you explain what mean the number is in "result_r_t.txt", and why your shader divide "scale" = 192.9. Thanks!

**Comment by gg-z** [comment]
The number in the "result_r_t.txt" has no meaning to u.
The "scale" is used to scale the model created by 3D maxs(the one I provided). Because the model reconstructed from images is not good, I use 3D maxs to reconstruct the object by hand. These two objects are aligned but the scale is different. So a scale is needed.
